# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1015, 607)
        MainWindow.setAutoFillBackground(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.ENC_1_Position = QtWidgets.QLCDNumber(self.centralwidget)
        self.ENC_1_Position.setGeometry(QtCore.QRect(0, 30, 161, 31))
        self.ENC_1_Position.setDigitCount(8)
        self.ENC_1_Position.setObjectName("ENC_1_Position")
        self.ENC_3_Position = QtWidgets.QLCDNumber(self.centralwidget)
        self.ENC_3_Position.setGeometry(QtCore.QRect(0, 150, 161, 31))
        self.ENC_3_Position.setDigitCount(8)
        self.ENC_3_Position.setObjectName("ENC_3_Position")
        self.ENC_2_Position = QtWidgets.QLCDNumber(self.centralwidget)
        self.ENC_2_Position.setGeometry(QtCore.QRect(0, 90, 161, 31))
        self.ENC_2_Position.setDigitCount(8)
        self.ENC_2_Position.setObjectName("ENC_2_Position")
        self.ENC_4_Position = QtWidgets.QLCDNumber(self.centralwidget)
        self.ENC_4_Position.setGeometry(QtCore.QRect(0, 210, 161, 31))
        self.ENC_4_Position.setDigitCount(8)
        self.ENC_4_Position.setObjectName("ENC_4_Position")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 161, 31))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(0, 50, 161, 51))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(0, 110, 151, 51))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(0, 170, 161, 51))
        self.label_4.setObjectName("label_4")
        self.ConnectToOmronBtn = QtWidgets.QPushButton(self.centralwidget)
        self.ConnectToOmronBtn.setGeometry(QtCore.QRect(0, 500, 161, 51))
        self.ConnectToOmronBtn.setObjectName("ConnectToOmronBtn")
        self.Error_Pos_AD = QtWidgets.QLCDNumber(self.centralwidget)
        self.Error_Pos_AD.setGeometry(QtCore.QRect(180, 150, 161, 31))
        self.Error_Pos_AD.setDigitCount(8)
        self.Error_Pos_AD.setObjectName("Error_Pos_AD")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(180, 0, 161, 31))
        self.label_5.setObjectName("label_5")
        self.Error_Pos_AB = QtWidgets.QLCDNumber(self.centralwidget)
        self.Error_Pos_AB.setGeometry(QtCore.QRect(180, 30, 161, 31))
        self.Error_Pos_AB.setDigitCount(8)
        self.Error_Pos_AB.setObjectName("Error_Pos_AB")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(180, 110, 151, 51))
        self.label_7.setObjectName("label_7")
        self.Error_Pos_AC = QtWidgets.QLCDNumber(self.centralwidget)
        self.Error_Pos_AC.setGeometry(QtCore.QRect(180, 90, 161, 31))
        self.Error_Pos_AC.setDigitCount(8)
        self.Error_Pos_AC.setObjectName("Error_Pos_AC")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(180, 50, 161, 51))
        self.label_8.setObjectName("label_8")
        self.ConnectToOmronBtn_2 = QtWidgets.QPushButton(self.centralwidget)
        self.ConnectToOmronBtn_2.setGeometry(QtCore.QRect(0, 250, 101, 51))
        self.ConnectToOmronBtn_2.setObjectName("ConnectToOmronBtn_2")
        self.ConnectToOmronBtn_3 = QtWidgets.QPushButton(self.centralwidget)
        self.ConnectToOmronBtn_3.setGeometry(QtCore.QRect(0, 300, 101, 51))
        self.ConnectToOmronBtn_3.setObjectName("ConnectToOmronBtn_3")
        self.ConnectToOmronBtn_4 = QtWidgets.QPushButton(self.centralwidget)
        self.ConnectToOmronBtn_4.setGeometry(QtCore.QRect(0, 350, 101, 51))
        self.ConnectToOmronBtn_4.setObjectName("ConnectToOmronBtn_4")
        self.ConnectToOmronBtn_5 = QtWidgets.QPushButton(self.centralwidget)
        self.ConnectToOmronBtn_5.setGeometry(QtCore.QRect(0, 400, 101, 51))
        self.ConnectToOmronBtn_5.setObjectName("ConnectToOmronBtn_5")
        self.ConnectToOmronBtn_6 = QtWidgets.QPushButton(self.centralwidget)
        self.ConnectToOmronBtn_6.setGeometry(QtCore.QRect(0, 450, 101, 51))
        self.ConnectToOmronBtn_6.setObjectName("ConnectToOmronBtn_6")
        self.EnableControlA = QtWidgets.QCheckBox(self.centralwidget)
        self.EnableControlA.setGeometry(QtCore.QRect(350, 40, 70, 17))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.EnableControlA.setFont(font)
        self.EnableControlA.setObjectName("EnableControlA")
        self.EnableControlB = QtWidgets.QCheckBox(self.centralwidget)
        self.EnableControlB.setGeometry(QtCore.QRect(350, 100, 70, 17))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.EnableControlB.setFont(font)
        self.EnableControlB.setObjectName("EnableControlB")
        self.EnableControlC = QtWidgets.QCheckBox(self.centralwidget)
        self.EnableControlC.setGeometry(QtCore.QRect(350, 160, 70, 17))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.EnableControlC.setFont(font)
        self.EnableControlC.setObjectName("EnableControlC")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1015, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt;\">Position A (deg) M</span></p></body></html>"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt;\">Position B (deg)</span></p></body></html>"))
        self.label_3.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt;\">Position C (deg)</span></p></body></html>"))
        self.label_4.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt;\">Position D (deg)</span></p></body></html>"))
        self.ConnectToOmronBtn.setText(_translate("MainWindow", "Connect"))
        self.label_5.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt;\">Error A - B (deg)</span></p></body></html>"))
        self.label_7.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt;\">Error A - D (deg)</span></p></body></html>"))
        self.label_8.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt;\">Error A - C (deg)</span></p></body></html>"))
        self.ConnectToOmronBtn_2.setText(_translate("MainWindow", "Home A"))
        self.ConnectToOmronBtn_3.setText(_translate("MainWindow", "Home B"))
        self.ConnectToOmronBtn_4.setText(_translate("MainWindow", "Home C"))
        self.ConnectToOmronBtn_5.setText(_translate("MainWindow", "Home D"))
        self.ConnectToOmronBtn_6.setText(_translate("MainWindow", "Home All"))
        self.EnableControlA.setText(_translate("MainWindow", "CheckBox"))
        self.EnableControlB.setText(_translate("MainWindow", "CheckBox"))
        self.EnableControlC.setText(_translate("MainWindow", "CheckBox"))
